import { defineRailway, postgres, preserve, project, service } from 'railway/iac'

// Railway infrastructure as code. Preview changes with `railway config plan`,
// apply them with `railway config apply`. Railway doesn't read this file
// during deploys; the template (or `config apply`) sets these values.
export default defineRailway(() => {
  const db = postgres('Postgres')

  const web = service('web', {
    // Railpack runs `npm run build`; Nitro outputs a self-contained server.
    start: 'node .output/server/index.mjs',
    // Apply Drizzle migrations (and seed a fresh database) before each
    // deployment starts. If this fails, the deploy stops.
    preDeploy: 'node scripts/migrate.mjs',
    // New deployments only receive traffic once this returns a 2xx.
    healthcheck: '/api/health',
    healthcheckTimeout: 60,
    env: {
      // Private network: postgres.railway.internal.
      DATABASE_URL: db.env.DATABASE_URL,
      // Generated by the template; kept as-is here.
      DISPATCH_PASSWORD: preserve(),
      SESSION_SECRET: preserve(),
      // Supplied by whoever deploys: Claude Code's key and a Railway token
      // for creating sandboxes. RAILWAY_ENVIRONMENT_ID is set by Railway.
      ANTHROPIC_API_KEY: preserve(),
      RAILWAY_API_TOKEN: preserve(),
    },
  })

  return project('dispatch', { resources: [db, web] })
})
