/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProjectIdRouteImport } from './routes/app.$projectId'
import { Route as AppAllRouteImport } from './routes/app.all'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppWebhooksRouteImport } from './routes/app.webhooks'
import { Route as ApiV1ProjectsRouteImport } from './routes/api.v1.projects'
import { Route as AppTaskTaskIdRouteImport } from './routes/app.task.$taskId'
import { Route as ApiV1ProjectsProjectIdRouteImport } from './routes/api.v1.projects.$projectId'
import { Route as ApiV1TasksTaskIdRouteImport } from './routes/api.v1.tasks.$taskId'
import { Route as ApiV1ProjectsProjectIdTasksRouteImport } from './routes/api.v1.projects.$projectId.tasks'
import { Route as ApiV1TasksTaskIdRunRouteImport } from './routes/api.v1.tasks.$taskId.run'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdRoute = AppProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppAllRoute = AppAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const ApiV1ProjectsRoute = ApiV1ProjectsRouteImport.update({
  id: '/api/v1/projects',
  path: '/api/v1/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTaskTaskIdRoute = AppTaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => AppRoute,
} as any)
const ApiV1ProjectsProjectIdRoute = ApiV1ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ApiV1ProjectsRoute,
} as any)
const ApiV1TasksTaskIdRoute = ApiV1TasksTaskIdRouteImport.update({
  id: '/api/v1/tasks/$taskId',
  path: '/api/v1/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProjectsProjectIdTasksRoute =
  ApiV1ProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => ApiV1ProjectsProjectIdRoute,
  } as any)
const ApiV1TasksTaskIdRunRoute = ApiV1TasksTaskIdRunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => ApiV1TasksTaskIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/app/$projectId': typeof AppProjectIdRoute
  '/app/all': typeof AppAllRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/app/': typeof AppIndexRoute
  '/api/v1/projects': typeof ApiV1ProjectsRouteWithChildren
  '/app/task/$taskId': typeof AppTaskTaskIdRoute
  '/api/v1/projects/$projectId': typeof ApiV1ProjectsProjectIdRouteWithChildren
  '/api/v1/tasks/$taskId': typeof ApiV1TasksTaskIdRouteWithChildren
  '/api/v1/projects/$projectId/tasks': typeof ApiV1ProjectsProjectIdTasksRoute
  '/api/v1/tasks/$taskId/run': typeof ApiV1TasksTaskIdRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/app/$projectId': typeof AppProjectIdRoute
  '/app/all': typeof AppAllRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/app': typeof AppIndexRoute
  '/api/v1/projects': typeof ApiV1ProjectsRouteWithChildren
  '/app/task/$taskId': typeof AppTaskTaskIdRoute
  '/api/v1/projects/$projectId': typeof ApiV1ProjectsProjectIdRouteWithChildren
  '/api/v1/tasks/$taskId': typeof ApiV1TasksTaskIdRouteWithChildren
  '/api/v1/projects/$projectId/tasks': typeof ApiV1ProjectsProjectIdTasksRoute
  '/api/v1/tasks/$taskId/run': typeof ApiV1TasksTaskIdRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/app/$projectId': typeof AppProjectIdRoute
  '/app/all': typeof AppAllRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/app/': typeof AppIndexRoute
  '/api/v1/projects': typeof ApiV1ProjectsRouteWithChildren
  '/app/task/$taskId': typeof AppTaskTaskIdRoute
  '/api/v1/projects/$projectId': typeof ApiV1ProjectsProjectIdRouteWithChildren
  '/api/v1/tasks/$taskId': typeof ApiV1TasksTaskIdRouteWithChildren
  '/api/v1/projects/$projectId/tasks': typeof ApiV1ProjectsProjectIdTasksRoute
  '/api/v1/tasks/$taskId/run': typeof ApiV1TasksTaskIdRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/api/health'
    | '/app/$projectId'
    | '/app/all'
    | '/app/settings'
    | '/app/webhooks'
    | '/app/'
    | '/api/v1/projects'
    | '/app/task/$taskId'
    | '/api/v1/projects/$projectId'
    | '/api/v1/tasks/$taskId'
    | '/api/v1/projects/$projectId/tasks'
    | '/api/v1/tasks/$taskId/run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/health'
    | '/app/$projectId'
    | '/app/all'
    | '/app/settings'
    | '/app/webhooks'
    | '/app'
    | '/api/v1/projects'
    | '/app/task/$taskId'
    | '/api/v1/projects/$projectId'
    | '/api/v1/tasks/$taskId'
    | '/api/v1/projects/$projectId/tasks'
    | '/api/v1/tasks/$taskId/run'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/api/health'
    | '/app/$projectId'
    | '/app/all'
    | '/app/settings'
    | '/app/webhooks'
    | '/app/'
    | '/api/v1/projects'
    | '/app/task/$taskId'
    | '/api/v1/projects/$projectId'
    | '/api/v1/tasks/$taskId'
    | '/api/v1/projects/$projectId/tasks'
    | '/api/v1/tasks/$taskId/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiV1ProjectsRoute: typeof ApiV1ProjectsRouteWithChildren
  ApiV1TasksTaskIdRoute: typeof ApiV1TasksTaskIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$projectId': {
      id: '/app/$projectId'
      path: '/$projectId'
      fullPath: '/app/$projectId'
      preLoaderRoute: typeof AppProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/all': {
      id: '/app/all'
      path: '/all'
      fullPath: '/app/all'
      preLoaderRoute: typeof AppAllRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/webhooks': {
      id: '/app/webhooks'
      path: '/webhooks'
      fullPath: '/app/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/v1/projects': {
      id: '/api/v1/projects'
      path: '/api/v1/projects'
      fullPath: '/api/v1/projects'
      preLoaderRoute: typeof ApiV1ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/task/$taskId': {
      id: '/app/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/app/task/$taskId'
      preLoaderRoute: typeof AppTaskTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/v1/projects/$projectId': {
      id: '/api/v1/projects/$projectId'
      path: '/$projectId'
      fullPath: '/api/v1/projects/$projectId'
      preLoaderRoute: typeof ApiV1ProjectsProjectIdRouteImport
      parentRoute: typeof ApiV1ProjectsRoute
    }
    '/api/v1/tasks/$taskId': {
      id: '/api/v1/tasks/$taskId'
      path: '/api/v1/tasks/$taskId'
      fullPath: '/api/v1/tasks/$taskId'
      preLoaderRoute: typeof ApiV1TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects/$projectId/tasks': {
      id: '/api/v1/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/api/v1/projects/$projectId/tasks'
      preLoaderRoute: typeof ApiV1ProjectsProjectIdTasksRouteImport
      parentRoute: typeof ApiV1ProjectsProjectIdRoute
    }
    '/api/v1/tasks/$taskId/run': {
      id: '/api/v1/tasks/$taskId/run'
      path: '/run'
      fullPath: '/api/v1/tasks/$taskId/run'
      preLoaderRoute: typeof ApiV1TasksTaskIdRunRouteImport
      parentRoute: typeof ApiV1TasksTaskIdRoute
    }
  }
}

interface AppRouteChildren {
  AppProjectIdRoute: typeof AppProjectIdRoute
  AppAllRoute: typeof AppAllRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWebhooksRoute: typeof AppWebhooksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTaskTaskIdRoute: typeof AppTaskTaskIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProjectIdRoute: AppProjectIdRoute,
  AppAllRoute: AppAllRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWebhooksRoute: AppWebhooksRoute,
  AppIndexRoute: AppIndexRoute,
  AppTaskTaskIdRoute: AppTaskTaskIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiV1ProjectsProjectIdRouteChildren {
  ApiV1ProjectsProjectIdTasksRoute: typeof ApiV1ProjectsProjectIdTasksRoute
}

const ApiV1ProjectsProjectIdRouteChildren: ApiV1ProjectsProjectIdRouteChildren =
  {
    ApiV1ProjectsProjectIdTasksRoute: ApiV1ProjectsProjectIdTasksRoute,
  }

const ApiV1ProjectsProjectIdRouteWithChildren =
  ApiV1ProjectsProjectIdRoute._addFileChildren(
    ApiV1ProjectsProjectIdRouteChildren,
  )

interface ApiV1ProjectsRouteChildren {
  ApiV1ProjectsProjectIdRoute: typeof ApiV1ProjectsProjectIdRouteWithChildren
}

const ApiV1ProjectsRouteChildren: ApiV1ProjectsRouteChildren = {
  ApiV1ProjectsProjectIdRoute: ApiV1ProjectsProjectIdRouteWithChildren,
}

const ApiV1ProjectsRouteWithChildren = ApiV1ProjectsRoute._addFileChildren(
  ApiV1ProjectsRouteChildren,
)

interface ApiV1TasksTaskIdRouteChildren {
  ApiV1TasksTaskIdRunRoute: typeof ApiV1TasksTaskIdRunRoute
}

const ApiV1TasksTaskIdRouteChildren: ApiV1TasksTaskIdRouteChildren = {
  ApiV1TasksTaskIdRunRoute: ApiV1TasksTaskIdRunRoute,
}

const ApiV1TasksTaskIdRouteWithChildren =
  ApiV1TasksTaskIdRoute._addFileChildren(ApiV1TasksTaskIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiV1ProjectsRoute: ApiV1ProjectsRouteWithChildren,
  ApiV1TasksTaskIdRoute: ApiV1TasksTaskIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
